#!/usr/bin/env python3
"""Generate Sphinx example pages from canonical example module docstrings."""

from __future__ import annotations

import argparse
import ast
import re
from dataclasses import dataclass
from pathlib import Path

REQUIRED_SECTIONS = (
    "Introduction",
    "Technical Implementation",
    "Expected Results",
    "References",
)
HEADING_CHARS = {
    "Introduction": "-",
    "Technical Implementation": "-",
    "Expected Results": "-",
    "References": "-",
    "Source Code": "-",
}


@dataclass(slots=True, frozen=True)
class ExampleDocSpec:
    """Represent one runnable example and its parsed canonical docs content."""

    rel_path: str
    slug: str
    title: str
    source_start_line: int
    sections: dict[str, str]


def _repo_root() -> Path:
    """Return the repository root path."""
    return Path(__file__).resolve().parents[1]


def _discover_examples(repo_root: Path) -> list[Path]:
    """Discover runnable Python example scripts."""
    examples_root = repo_root / "examples"
    return [
        path
        for path in sorted(examples_root.rglob("*.py"))
        if "__pycache__" not in path.parts
        and "artifacts" not in path.parts
        and not path.name.startswith("_")
    ]


def _parse_module_doc_text(path: Path) -> tuple[str, int]:
    """Parse module docstring text and source start line from one example."""
    source = path.read_text(encoding="utf-8")
    module = ast.parse(source, filename=str(path))
    docstring = ast.get_docstring(module, clean=False)
    if not isinstance(docstring, str) or not docstring.strip():
        raise ValueError(f"{path}: missing module docstring.")
    source_start_line = 1
    if module.body:
        first = module.body[0]
        if (
            isinstance(first, ast.Expr)
            and isinstance(first.value, ast.Constant)
            and isinstance(first.value.value, str)
            and isinstance(first.end_lineno, int)
        ):
            source_start_line = first.end_lineno + 1
    lines = source.splitlines()
    while source_start_line <= len(lines) and not lines[source_start_line - 1].strip():
        source_start_line += 1
    return docstring, source_start_line


def _parse_sections(*, doc_text: str, source_path: Path) -> dict[str, str]:
    """Parse canonical ``##`` sections from one example docstring."""
    heading_pattern = re.compile(r"^##\s+(.+?)\s*$")
    sections: dict[str, list[str]] = {}
    current: str | None = None
    for raw_line in doc_text.splitlines():
        line = raw_line.rstrip()
        match = heading_pattern.match(line.strip())
        if match is not None:
            heading = match.group(1).strip()
            current = heading if heading in REQUIRED_SECTIONS else None
            if current is not None:
                sections[current] = []
            continue
        if current is not None:
            sections[current].append(line)
    missing = [section for section in REQUIRED_SECTIONS if section not in sections]
    if missing:
        raise ValueError(f"{source_path}: missing canonical section(s): {missing}")
    return {heading: "\n".join(body).strip() for heading, body in sections.items()}


def _slug_for_example(path: Path, repo_root: Path) -> str:
    """Build a deterministic slug from one example path."""
    return path.relative_to(repo_root / "examples").with_suffix("").as_posix().replace("/", "_")


def _title_for_example(path: Path) -> str:
    """Build a human-readable title from one example filename."""
    return path.stem.replace("_", " ").title()


def _build_example_specs(repo_root: Path) -> list[ExampleDocSpec]:
    """Parse all example docstrings into documentation specs."""
    specs: list[ExampleDocSpec] = []
    for path in _discover_examples(repo_root):
        doc_text, source_start_line = _parse_module_doc_text(path)
        specs.append(
            ExampleDocSpec(
                rel_path=path.relative_to(repo_root).as_posix(),
                slug=_slug_for_example(path, repo_root),
                title=_title_for_example(path),
                source_start_line=source_start_line,
                sections=_parse_sections(doc_text=doc_text, source_path=path),
            )
        )
    return specs


def _heading(title: str, char: str = "=") -> str:
    """Render one reStructuredText heading."""
    return f"{title}\n{char * len(title)}"


def _render_example_page(spec: ExampleDocSpec) -> str:
    """Render one generated example documentation page."""
    parts = [
        ".. This file is generated by scripts/generate_example_docs.py.",
        "",
        _heading(spec.title),
        "",
        f"Source: ``{spec.rel_path}``",
        "",
    ]
    for section in REQUIRED_SECTIONS:
        body = spec.sections[section]
        parts.extend(
            [
                _heading(section, HEADING_CHARS[section]),
                "",
                body,
                "",
            ]
        )
    parts.extend(
        [
            _heading("Source Code", HEADING_CHARS["Source Code"]),
            "",
            f".. literalinclude:: ../../{spec.rel_path}",
            "   :language: python",
            "   :linenos:",
            f"   :lines: {spec.source_start_line}-",
            "",
        ]
    )
    return "\n".join(parts).rstrip() + "\n"


def _render_examples_index(specs: list[ExampleDocSpec]) -> str:
    """Render the generated examples index page."""
    lines = [
        ".. This file is generated by scripts/generate_example_docs.py.",
        "",
        _heading("Examples"),
        "",
        "The examples are part of the maintained public contract for `mcpme`.",
        "Each page below is generated from the example module docstring and the",
        "checked-in source file, so the code and prose stay aligned.",
        "",
        ".. toctree::",
        "   :maxdepth: 1",
        "",
    ]
    lines.extend(f"   {spec.slug}" for spec in specs)
    lines.extend(
        [
            "",
            "Example Inventory",
            "-----------------",
            "",
        ]
    )
    for spec in specs:
        first_line = spec.sections["Introduction"].splitlines()[0].strip()
        lines.append(f"- ``{spec.rel_path}``: {first_line}")
    lines.append("")
    return "\n".join(lines)


def _write_if_changed(path: Path, content: str) -> bool:
    """Write one file only when the rendered content changed."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _expected_outputs(repo_root: Path, specs: list[ExampleDocSpec]) -> dict[Path, str]:
    """Return the generated docs paths and their expected contents."""
    docs_root = repo_root / "docs" / "examples"
    outputs = {docs_root / "index.rst": _render_examples_index(specs)}
    for spec in specs:
        outputs[docs_root / f"{spec.slug}.rst"] = _render_example_page(spec)
    return outputs


def _check(outputs: dict[Path, str]) -> int:
    """Check that generated example docs are up to date."""
    mismatches = [
        path
        for path, content in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    existing_generated = {
        path
        for path in (next(iter(outputs)).parent).glob("*.rst")
        if path.name != "index.rst" or path in outputs
    }
    extras = sorted(existing_generated - set(outputs))
    if mismatches or extras:
        for path in mismatches:
            print(f"Out-of-date generated example docs: {path}")
        for path in extras:
            print(f"Unexpected generated example docs file: {path}")
        return 1
    print("Generated example docs are up to date.")
    return 0


def _write(outputs: dict[Path, str]) -> int:
    """Write the generated example docs to disk."""
    changed = 0
    docs_root = next(iter(outputs)).parent
    docs_root.mkdir(parents=True, exist_ok=True)
    expected_paths = set(outputs)
    for existing in docs_root.glob("*.rst"):
        if existing not in expected_paths:
            existing.unlink()
            changed += 1
    for path, content in outputs.items():
        changed += int(_write_if_changed(path, content))
    print(f"Generated example docs updated ({changed} file(s) changed).")
    return 0


def main() -> int:
    """Generate or check example documentation pages."""
    parser = argparse.ArgumentParser(description="Generate Sphinx pages for runnable examples.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify that generated docs are current.",
    )
    args = parser.parse_args()

    repo_root = _repo_root()
    specs = _build_example_specs(repo_root)
    outputs = _expected_outputs(repo_root, specs)
    return _check(outputs) if args.check else _write(outputs)


if __name__ == "__main__":
    raise SystemExit(main())
